# Generated by Django 4.0.4 on 2022-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displacement',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
    ]
