# Generated by Django 4.0.4 on 2022-06-06 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_cart_cartitem_cart_id_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
