# Generated by Django 4.0.4 on 2022-06-07 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_rename_cart_id_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('building', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10, null=True, unique=True)),
                ('alt_mobile', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
