# Generated by Django 4.0.4 on 2022-06-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
