# Generated by Django 4.0.4 on 2022-06-11 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_account_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
        ),
    ]
