# Generated by Django 4.0.4 on 2022-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='razpayment_id',
            field=models.CharField(default=0, max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Shipped', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='signature_id',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
