# Generated by Django 4.0.4 on 2022-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='checksum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
